### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [sjmackenzie/rlp2#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by sjmackenzie** [comment]
`rlp2` hasn't been been published yet. We'll need to refactor this repo to suit `SputnikVM`'s needs soon actually. I also drop `rustc-serialize` in the process. (Huge respect to you for deprecating `rustc-serialize` in his fashion.)
